---
spring:
  application:
    environment: systest

issuer-ui-demo:
  issuer-server:
    base-url: https://utsteder.eidas2sandkasse.dev

maskinporten:
  oauth2:
    issuer: https://test.maskinporten.no/
