# See https://github.com/felleslosninger/github-workflows for reusable workflows used.

name: Build/publish Docker image & update image version in config

on:
  push:
    branches: [main]
    paths-ignore:
      - "src/test/**"
      - "docker/**"
      - "docker-compose*.yaml"
      - "*.md"
      - "LICENSE"
      - "catalog-info.yaml"

jobs:
  build-publish-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      image-name: digital-lommebok-issuer-ui-demo
      java-version: 24
    secrets: inherit

  call-update-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    needs: build-publish-image
    with:
      application-name: digital-lommebok-issuer-ui-demo
      deployment-environment: systest
      image-digest: ${{ needs.build-publish-image.outputs.image-digest }}
      image-name: digital-lommebok-issuer-ui-demo
      image-version: ${{ needs.build-publish-image.outputs.image-version }}
      kubernetes-repo: digital-lommebok-cd
      product-name: digital-lommebok
    secrets: inherit
